name: job-dashboard

services:
    frontend:
        build:
            context: .
        ports:
            - "3000:3000"
        depends_on:
            - backend
    backend:
        build:
            context: ./backend
        ports:
            - "5000:5000"
networks:
    job-search-network:
        driver: bridge
